language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - curl --silent http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

env:
  - CHECKZONE_PATH="named-checkzone"

script: phpunit --coverage-text

notifications:
  email:
    - sam@badcow.co